FROM node:16.17.0-bullseye-slim

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ENV MONGODB_URI=mongodb://host.docker.internal:27017/yobulk
ENV DATABASE_NAME=yobulk
ENV OPENAI_SECRET_KEY=YOUR_OPENAI_SECRET_KEY
ENV BACKEND_SERVER_HOST="http://localhost:5050"

COPY . .
EXPOSE 5050

CMD ["yarn", "dev"]